name: quick_drop
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.4.1

dependencies:
  country_picker: ^2.0.26
  cupertino_icons: ^1.0.8
  dio: ^5.6.0
  file_picker: ^8.1.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_screenutil: ^5.7.0
  freezed_annotation: ^2.4.4
  get: ^4.6.6
  google_fonts: ^4.0.3
  image_picker: ^1.1.2
  intl: ^0.19.0
  intl_phone_number_input: ^0.7.4
  pinput: ^5.0.0
  shared_preferences: ^2.3.2
  signature: ^5.0.0
  timeline_tile: ^2.0.0
  toastification: ^2.2.0

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/appIcon.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/profile.jpg
